<a href="https://colab.research.google.com/github/Utkarsh472/Python-Numpy/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Data Types


In [ ]:
import numpy as np

my_array = np.array([10,12,14,16,20,25])

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10 12 14 16 20 25]
int64
8


In [ ]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [ ]:
import numpy as np

my_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"])

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
<U10
40


In [ ]:
my_array3 = my_array.astype("M")

print(my_array3.dtype)
print(my_array3.dtype.itemsize)

datetime64[D]
8


In [ ]:
import numpy as np

my_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"], dtype = "M")

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
datetime64[D]
8


Creating NumPy Arrays

1) Using Array Method



In [ ]:
import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array) 

numpy.ndarray

In [ ]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
nums_2d.shape 

(3, 3)

2) Using Arange Method

In [ ]:
nums_arr = np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [ ]:
nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


3) Using Ones Method

In [ ]:
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [ ]:
ones_array = np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4) Using Zeros Method

In [ ]:
zeros_array = np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [ ]:
zeros_array = np.zeros((6,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


5) Using Eyes Method

In [ ]:
eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


6) Using Random Method

In [ ]:
uniform_random = np.random.rand(4, 5)
print(uniform_random)

[[0.62364156 0.61490848 0.40883929 0.37003894 0.22329996]
 [0.90634775 0.60977995 0.64338431 0.01557602 0.11655535]
 [0.92783892 0.48728126 0.77749427 0.00868098 0.41949436]
 [0.55715253 0.58927218 0.69956312 0.19211557 0.41317187]]


In [ ]:
normal_random = np.random.randn(4, 5)
print(uniform_random)

[[0.62364156 0.61490848 0.40883929 0.37003894 0.22329996]
 [0.90634775 0.60977995 0.64338431 0.01557602 0.11655535]
 [0.92783892 0.48728126 0.77749427 0.00868098 0.41949436]
 [0.55715253 0.58927218 0.69956312 0.19211557 0.41317187]]


In [ ]:
integer_random = np.random.randint(10, 50, 5)
print(integer_random)

[16 33 48 46 35]


Printing NumPy Arrays

In [1]:
import numpy as np

my_array = np.array([10,12,14,16,20,25])
print(my_array)

[10 12 14 16 20 25]


In [2]:
print(my_array.ndim)
print(my_array.shape)

1
(6,)


In [3]:
for i in my_array:
    print(i)

10
12
14
16
20
25


In [4]:
integer_random = np.random.randint(1,11, size=(4, 5))
print(integer_random)

[[ 7  9  8  5  9]
 [10  4  7  6  2]
 [ 8  3 10  8  2]
 [ 8  3  1  2  4]]


In [5]:
print(integer_random.ndim)
print(integer_random.shape)

2
(4, 5)


In [6]:
for i in integer_random:
    print(i)

[7 9 8 5 9]
[10  4  7  6  2]
[ 8  3 10  8  2]
[8 3 1 2 4]


In [7]:
for rows in integer_random:
    for column in rows:
        print(column)

7
9
8
5
9
10
4
7
6
2
8
3
10
8
2
8
3
1
2
4


Adding Items in an Array

In [8]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])
print(my_array)

extended = np.append(my_array, "Yellow")
print(extended)

['Red' 'Green' 'Orange']
['Red' 'Green' 'Orange' 'Yellow']


In [9]:
zeros_array = np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
zeros_array = np.zeros((3,3))
print(zeros_array)
print("Extended Array")
extended = np.append(zeros_array, [[1, 2, 3]], axis = 0)
print(extended)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 2. 3.]]


In [11]:
zeros_array = np.zeros((3,3))
print(zeros_array)
print("Extended Array")
extended = np.append(zeros_array, [[1],[2],[3]], axis = 1)
print(extended)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array
[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]]


Removing Items from Array

In [18]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])
print(my_array)

print("After deletion")
updated_array = np.delete(my_array, 2)
print(updated_array)

['Red' 'Green' 'Orange']
After deletion
['Red' 'Green']


In [20]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])
print(my_array)

print("After deletion")
updated_array = np.delete(my_array, [0,2])
print(updated_array)

['Red' 'Green' 'Orange']
After deletion
['Green']


In [22]:
integer_random = np.random.randint(1,11, size=(4, 5))
print(integer_random)

print("After deletion")
updated_array = np.delete(integer_random, 2, axis = 0)
print(updated_array)

[[10  4  9  8  6]
 [ 3  7 10  4  9]
 [ 2  9  3  4  1]
 [ 5  2  2  8  6]]
After deletion
[[10  4  9  8  6]
 [ 3  7 10  4  9]
 [ 5  2  2  8  6]]


In [24]:
integer_random = np.random.randint(1,11, size=(4, 5))
print(integer_random)

print("After deletion")
updated_array = np.delete(integer_random, 1, axis = 1)
print(updated_array)

[[ 5  8  9 10  6]
 [ 1  3  5  8  1]
 [ 9  3  5  8  6]
 [ 8  7  9  9  8]]
After deletion
[[ 5  9 10  6]
 [ 1  5  8  1]
 [ 9  5  8  6]
 [ 8  9  9  8]]


Q) Create a random (4,5) array

In [25]:
import numpy as np
uniform_random = np.random.rand(4, 5)
print(uniform_random)

[[0.95107304 0.51316335 0.03475477 0.08849175 0.42902537]
 [0.83938568 0.34166387 0.42659656 0.04496641 0.78414176]
 [0.87660055 0.71308637 0.03105236 0.20902169 0.34236186]
 [0.33628484 0.17731723 0.84706679 0.63572887 0.40869922]]
