<a href="https://colab.research.google.com/github/Utkarsh472/Python-Numpy/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas for Data Manipulation

In [2]:
import pandas as pd

A pandas Series is a one-dimensional labelled data structure which can hold data such as strings, integers and even other Python objects. It is built on top of numpy array and is the primary data structure to hold one-dimensional data in pandas


In [3]:
data=pd.Series([0.25,0.50,0.75,0.95],index=['a','b','c','d'])
data.values

array([0.25, 0.5 , 0.75, 0.95])

In [4]:
print(type(data.values))
print(type(data))


<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [5]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [6]:
print(data['a'])
print(data['b'])

0.25
0.5


In [7]:
print(data['a':'c'])

a    0.25
b    0.50
c    0.75
dtype: float64


In [8]:
grades_dict={'A':4,'B':5,'C':6,'D':8}
grades=pd.Series(grades_dict)
print(grades)

A    4
B    5
C    6
D    8
dtype: int64


In [9]:
marks_dict={'A':85,'B':70,'C':40,'D':30}
marks=pd.Series(marks_dict)
print(marks)

A    85
B    70
C    40
D    30
dtype: int64


In [10]:
grades.values

array([4, 5, 6, 8])

In [11]:
grades.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [12]:
grades['A']

4

In [13]:
grades[0:3]

A    4
B    5
C    6
dtype: int64

Pandas: DataFrame 

In [14]:

df=pd.DataFrame({'Grades':grades,'Marks':marks})
df

Grades  Marks
A       4     85
B       5     70
C       6     40
D       8     30

In [15]:
df.T

A   B   C   D
Grades   4   5   6   8
Marks   85  70  40  30

In [16]:
df.values

array([[ 4, 85],
       [ 5, 70],
       [ 6, 40],
       [ 8, 30]])

In [17]:
df.values[2,0]
#To access 6 value

6

In [18]:
df.columns

Index(['Grades', 'Marks'], dtype='object')

In [19]:
df['ScaledMarks']=(df['Grades']/90)*100;
df

Grades  Marks  ScaledMarks
A       4     85     4.444444
B       5     70     5.555556
C       6     40     6.666667
D       8     30     8.888889

In [20]:
rank_dict={'A':1,'B':2,'C':3,'D':4}
rank=pd.Series(rank_dict)
print(rank)


A    1
B    2
C    3
D    4
dtype: int64


In [21]:
df['rank']=rank

In [22]:
df

Grades  Marks  ScaledMarks  rank
A       4     85     4.444444     1
B       5     70     5.555556     2
C       6     40     6.666667     3
D       8     30     8.888889     4

In [23]:
frame=df[df['Marks']>=40]
frame

Grades  Marks  ScaledMarks  rank
A       4     85     4.444444     1
B       5     70     5.555556     2
C       6     40     6.666667     3

Pandas Missing Values

In [27]:
df=pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])
df

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [28]:
df.fillna(0) #to fill something to missing values

a  b    c
0  1.0  2  0.0
1  0.0  3  4.0

In [29]:
df=pd.Series(['a','b','c'],index=[1,3,5])
df

1    a
3    b
5    c
dtype: object

In [30]:
df[1] #explicit indices

'a'

In [31]:
df[1:3]#implicit indices

3    b
5    c
dtype: object

In [32]:
df.loc[1:3]

1    a
3    b
dtype: object

In [33]:
df.iloc[1:3]

3    b
5    c
dtype: object

In [34]:
frame

Grades  Marks  ScaledMarks  rank
A       4     85     4.444444     1
B       5     70     5.555556     2
C       6     40     6.666667     3

In [38]:
frame.iloc[0:2]

Grades  Marks  ScaledMarks  rank
A       4     85     4.444444     1
B       5     70     5.555556     2

In [46]:
frame.iloc[0,1]

85

In [54]:
frame.iloc[1,:]

Grades          5.000000
Marks          70.000000
ScaledMarks     5.555556
rank            2.000000
Name: B, dtype: float64

In [55]:
frame.iloc[:1,:]

Grades  Marks  ScaledMarks  rank
A       4     85     4.444444     1

In [57]:
frame.iloc[1:,:]

Grades  Marks  ScaledMarks  rank
B       5     70     5.555556     2
C       6     40     6.666667     3

In [50]:
 frame.iloc[::-1,:]

Grades  Marks  ScaledMarks  rank
C       6     40     6.666667     3
B       5     70     5.555556     2
A       4     85     4.444444     1

In [51]:
frame.iloc[::-1,0]

C    6
B    5
A    4
Name: Grades, dtype: int64